name: Push to output repo

on:
    push:


jobs:
  push-to-output-repo:

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Set up packages
      run: pacman -Syu --noconfirm --needed git

    - name: Clone repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run:
        git clone https://angelofallars:$API_TOKEN_GITHUB@github.com/angelofallars/output-repo.git

    - name: List files
      run:
        ls -R -a
