name: Push to output repo

on:
    push:


jobs:
  push-to-output-repo:

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Set up packages
      run: pacman -Syu --noconfirm --needed git

    - name: Set up identity
      run: |
           git config --global user.email "ba.fallaria@gmail.com"
           git config --global user.name "Angelo Fallaria"

    - name: Clone repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run:
        git clone https://angelofallars:$API_TOKEN_GITHUB@github.com/angelofallars/output-repo.git

    - name: List files
      run:
        ls -R -a
    
    - name: Add file then commit
      working-directory: ./output-repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        touch wooshwow
        git add wooshwow
        git status
        git commit --message "feat: add a file"
        git push https://angelofallars:$API_TOKEN_GITHUB@github.com/angelofallars/output-repo.git --set-upstream origin main
